name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Run checks
        run: make check

  type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}

      # TODO: re-enable tests when we have an environment that doesn't require a GPU for CI testing
      #     - name: Run tests
      #       run: uv run python -m pytest tests

      - name: Check typing
        run: uv run mypy


  # TODO: re-enable documentation checks when we start documentation
  # check-docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out
  #       uses: actions/checkout@v4
  #      with:
  #        submodules: true


  #     - name: Set up the environment
  #       uses: ./.github/actions/setup-python-env

  #     - name: Check if documentation can be built
  #       run: uv run mkdocs build -s
